version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit:/var/lib/rabbitmq
  # elastic:
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
  #   volumes:
  #     - 'es_data:/usr/share/elasticsearch/data'
  #   ports:
  #     - "9200:9200"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  db:
    image: postgres
    ports:
      - "8001:5432"
  # crawler:
  #   build: ./crawler
  #   links:
  #     - rabbitmq
  #     - elastic
  #   depends_on:
  #     - "rabbitmq"
  #     - "elastic"
  #   restart: "on-failure"
  auth:
    build: ./authserver
    depends_on:
      - "rabbitmq"
  # api:
  #   build: ./api
  #   depends_on:
  #     - "rabbitmq"
  #     - "elastic"
  #     - "db"
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - "db"

volumes:
  es_data:
  rabbit:
